server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
aliyun:
  oss:
    file:
      endpoint: oss-cn-guangzhou.aliyuncs.com
      keyid: LTAI5t7K8aK6UJvYRNzuYHVE
      keysecret: yLekhaM0r9MGIjBwG7JVavz5uvLc4k
      bucketname: edu-3-1